### ISSUE TITLE
Explain that it's ok for build scripts and proc macros to panic

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/api-guidelines#104]
In the section about not panicking, we need to also explain that there are cases where panicking is the accepted strategy. In most build scripts and crates that are intended to be used primarily in build scripts, errors result in panicks.

Explain this, but also that it's important to provide `try_` methods if it's possible the code won't be used at build time. Also that the panic messages must be awesome.

**Comment by dtolnay** [comment]
I don't think we have or need a section about not panicking. This is sufficiently covered by [To panic! or Not To panic!](https://doc.rust-lang.org/book/second-edition/ch09-03-to-panic-or-not-to-panic.html).
