### ISSUE TITLE
C-HIERARCHY is vague and probably unactionable

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/api-guidelines#107]
It basically just exhorts the reader to be "sensible", and gives a couple specific examples of where serde does something that is claimed to be sensible. Needs to be some firmer advice here.

**Comment by dtolnay** [comment]
I deleted both C-HIERARCHY and C-REEXPORT in 40253465120726e9a1925a891c8102b952efd05b. Neither one was able to give firm enough advice to warrant a guideline.
