### ISSUE TITLE
C-CONV: Uses an inadequate std example

### ISSUE THREAD

**Issue by TheDan64** [rust-lang-nursery/api-guidelines#112]
Under the C-CONV section, it states that `to_*` methods go from borrowed -> owned and is an expensive operation (usually involving a clone)

However, in the "more examples from the std library", it references [Path::to_str](https://doc.rust-lang.org/std/path/struct.Path.html#method.to_str), which has a signature of `fn to_str(&self) -> Option<&str>`. This seems like this method should have actually been named `as_str` according to these guidelines, and is therefore a inadequate example for `to_*` methods.

Edit: Only thing I can think of is maybe it's costly to validate UTF8 from the inner OsStr?

**Comment by dtolnay** [comment]
Thanks for catching this! The `Path::to_str` pattern is indeed not covered by the table. I added an explanation in ed624dbd5f3a5f234426543ee90cf695b905638b. It would not be correct to call this `as_str` because the method has a non-negligible cost at runtime.
