### ISSUE TITLE
[C-METADATA] package.documentation should be optional

### ISSUE THREAD

**Issue by behnam** [rust-lang-nursery/api-guidelines#117]
The `package.documentation` now has a reasonable default value, using *docs.rs*, meaning that it actually makes sense to not have it specifically set for most crates. 

Therefore, it makes sense to update C-METADATA to mention this default value and ask the config to be set only if it's not the default *docs.rs* link. This exception would be similar to the `package.homepage` config.

**Comment by dtolnay** [comment]
Thanks! I removed the docs.rs guideline in b7a831ea4fc9a091e2bf575501019790dd9598f7 and explained that the `documentation` metadata in Cargo.toml is optional in 17073b7bdf0e5fa70d71e6f814f001869aac0ea3.
