### ISSUE TITLE
How to decide whether to provide Serde impls

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#12]
Currently the only guideline is:

> Most types should implement serde's Serialize, Deserialize (C-SERDE)

Of the crates that the libs team has covered so far (byteorder, bitflags, tempdir, flate2) we decided that none need Serde impls. The guideline should be rephrased or clarified to incorporate our reasoning.

**Comment by brson** [comment]
Add some more color here.

**Comment by dtolnay** [comment]
See #64 for a particular example.

**Comment by dtolnay** [comment]
I added more color in 5b64a7b56ea625688e8006f03359b3f42d6a0ee7.
