### ISSUE TITLE
Use the latest version of mdBook

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#129]
I'm not sure why https://github.com/rust-lang-nursery/api-guidelines/commit/68e1ac11c852c9094b5e5f12312c4eeae09fec03#diff-354f30a63fb0907d4ad57269548329e3 decided to pin to a specific version but I think it should be okay to always build with the latest version. We can temporarily pin later if anything goes wrong.

This requires adjusting the caching from #128 so that new versions get picked up. Maybe something like:

```sh
[ -f ~/.cargo/bin/cargo-install-update ] || cargo install cargo-update
cargo install-update mdbook cargo-update
```

@mgeisler

**Comment by mgeisler** [comment]
I had first imagined that a simple `cargo install --force mdbook` would be enough, but I just learned that `cargo install` recompiles all the dependencies of `mdbook` on every install... so something like you suggest is probably better :-)

I'll be happy to take a look at this.
