### ISSUE TITLE
Naming convention for macros

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#135]
The C-CASE table needs a line for macros. I believe the convention is `snake_case!`.

**Comment by dtolnay** [comment]
Added in f59ec10024341930e982fb5425e26ea63a00d74a.

**Comment by ExpHP** [comment]
Should this recommendation be applied unilaterally, or is it more subtle?  I've been using `PascalCase!` for macros that expand into types.

**Comment by dtolnay** [comment]
Thanks! I did not consider type macros when I wrote this. I filed #145 to follow up.
