### ISSUE TITLE
Guideline about extern crate

### ISSUE THREAD

**Issue by AlexEne** [rust-lang-nursery/api-guidelines#139]
Let's say we have a simple library with the following structure:
```
src\
    lib.rs
    file1.rs
    file2.rs
    [...]
```
We have two options if we want to use an extern crate in both file1 and file2.

1) We  can either use ```extern crate crate_name;``` once in lib.rs and in all the other files we can have ```use crate_name;```.

2) Another option that works (surprisingly to me) is having ```extern crate crate_name;``` in each of the files that want to use things from that crate.

Neither the compiler, nor clippy complains about any of the approaches, yet in practice I've seen libraries like rayon and others that prefer to have all ```extern crate``` at the lib.rs level.

I think a guideline around this would be helpful, my preferred variant is 1) and I see that this resonated with some ppl from the cookbook chat room so I have decided to open this issue here.

Arguments for 1 in my view are:
- Less clutter at the top of the file (at least we keep it to mostly ```use ...``` statements.
- Better readability for determining dependencies for non-cargo built projects since you can see all extern deps in one place? Or am I wrong about this one?
- There is no reason to to repeat the extern crate thing for each file.
- ```use file1::crate_name;``` is even more confusing if the place where you decide to do the extern crate is not lib.rs/mod.rs/main.rs.
- Are there any technical advantages besides de-cluttering that are worth mentioning?
- What about crates used in only one file? Should we still do extern crate in lib.rs?
- Is it even worth mentioning as a guideline ?

**Comment by dtolnay** [comment]
Personally I typically use `extern crate` only in lib.rs except where required for technical reasons in macro-generated code.

I don't think this would belong in the API guidelines because it does not affect the API of a crate. Either way results in the same public API. If you feel strongly that `extern crate` outside of lib.rs should be discouraged, I would file an issue against Clippy and have them implement a lint to warn about it (or get mentorship and implement the lint in a PR).

**Comment by AlexEne** [comment]
I don't feel strongly about it at all. It was just a bit hard in finding the answer to this question or if it had any implications (other than being tidy). 
Since it has no side-effects, I am closing this.
