### ISSUE TITLE
Error handling and quick-error (C-GOOD-ERR)

### ISSUE THREAD

**Issue by tailhook** [rust-lang-nursery/api-guidelines#144]
I have two questions:

1. What do you think about recommending `quick-error` for error handling? The guide barely mentions `error-chain` but doesn't recommend it either. I think quick-error is much more lightweight, and basically does what is recommended here out of the box.

2. The recent addition to docs says that `description()` isn't particularly useful. Do you think it's good idea to deprecate `description()` in `quick-error` itself? If you omit description in macro, it generates description which is equal to enum variant name, which might be enough to implement the trait. And in reality, I have never used or seen description used anywere.

Any thoughts are appreciated.

**Comment by dtolnay** [comment]
1. I would be inclined to recommend [`failure`](https://github.com/withoutboats/failure) once it has been published, and remove references to error-chian. Failure is built on lessons learned from error-chain, quick-error, and the standard library's errors.

2. Yes customization of `description` should be deprecated.

**Comment by tailhook** [comment]
Yes, `failure` crate looks interesting at a glance. Should investigate it better. Thanks!
