### ISSUE TITLE
Private supertrait pattern

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#16]
This pattern is a way to retain the ability to add/remove/modify methods of a public trait without breaking compatibility. Example from byteorder: https://github.com/BurntSushi/byteorder/issues/69.

**Comment by dtolnay** [comment]
Relevant discussion in the context of Hyper: https://github.com/hyperium/hyper/issues/1194

**Comment by dtolnay** [comment]
Added in e7d7202eceea3357ff87e1026ed9000b927fb4aa.

**Comment by matklad** [comment]
@dtolnay curious, why we put `#[doc(hidden)]` on the methods of the public trait, if we can just add these methods to the private counterpart? That is, something [like this](https://play.rust-lang.org/?gist=74d4fb177223b3a3b1459f08bcaad12e&version=stable&mode=debug&edition=2015) should work?

I don't think that it matters much in practice, but `doc(hidden)` methods are still visible, and might cause ambiguous method calls in theory....
