### ISSUE TITLE
`_move` suffix?

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#37]
> If `foo` uses/produces an immutable borrow by default, use:
>
> - The `_mut` suffix (e.g. `foo_mut`) for the mutably borrowed variant.
> - The `_move` suffix (e.g. `foo_move`) for the owned variant.

Is `_move` this still encouraged? What is a good example from the standard library?

**Comment by brson** [comment]
Remove from guidleines.
