### ISSUE TITLE
Mutable accessor for Copy single-element Cell-like container

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#44]
The guideline says:

> Single-element containers where the element is Copy (e.g. Cell-like containers) should instead return the value directly, and not implement a mutable accessor.

And yet: [`Cell::get_mut`](https://doc.rust-lang.org/std/cell/struct.Cell.html#method.get_mut)

**Comment by Rufflewind** [comment]
That guideline is quite confusing.  Why does the presence of `Copy` make mutable accessors undesirable?

**Comment by jonas-schievink** [comment]
@Rufflewind My guess is that `set` should be used to put a new value into the container.

`Cell::get_mut` is no longer limited to `Copy` types, by the way, so it now matches the guideline.

**Comment by dtolnay** [comment]
Cell now works for non-Copy types and exposes get_mut for them, so I removed this special case from the guidelines in ee56222375cf3de2599f3f6c09514b5b43211898.
