### ISSUE TITLE
Discourage renaming in `pub use` re-exports

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#5]
In flate2 the write/read/bufread modules all repeat the same type names:

```rust    
pub use gz::EncoderReader as flate2::read::GzEncoder;
pub use deflate::EncoderReader as flate2::read::DeflateEncoder;
```

Unfortunately the [rustdoc for `flate2::read::GzEncoder`](https://docs.rs/flate2/0.2.17/flate2/read/struct.GzEncoder.html) shows the private names:

```rust
impl<R: Read> EncoderReader<R>
fn new(r: R, level: Compression) -> EncoderReader<R>
```

This is a rustdoc bug (https://github.com/rust-lang/rust/issues/41072) but even aside from that, this pattern is confusing to people browsing the code because what they see clicking through a [src] link does not match how they will be using the library. Let's discourage renames in `pub use` unless there is a very good reason, and give an example of a very good reason from a high-quality crate.

**Comment by brson** [comment]
Add to 'naming'.

**Comment by dtolnay** [comment]
I don't think this is a common enough problem to need a guideline.
