### ISSUE TITLE
Crate naming: never use -rs or -rust suffix

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#57]
We already know what language we are writing.

**Comment by lfairy** [comment]
I've seen that used because the name without the suffix was already taken. But in those cases I think it's better to choose a different name anyway.

**Comment by dtolnay** [comment]
Right. If crate `lfairy` already exists so you call it `lfairy-rs`, in my opinion that is even less inspired than calling it `lfairy2`.

**Comment by Kixunil** [comment]
This is true for crates themselves. I find repositories having -rs suffix useful if the name would be otherwise identical to some popular library from other language. (e.g. if repo is called `json-rs` I immediately know it's Rust crate.)

**Comment by lfairy** [comment]
Note that Cargo strips `-rs` and `rust-` from the crate name in `cargo new`, so you have to work to circumvent this rule. See rust-lang/cargo#1532.

**Comment by dtolnay** [comment]
Added in c501a0b1bce31966bfe135a2cac30bad2036c0ba.
