### ISSUE TITLE
Guideline for importing macro_rules! macros

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/api-guidelines#68]
Discussed during the `log` evaluation, we should have a guideline that each macro is selectively importable via `#[macro_use(foo)]`. We'll want to document the caveats here (duplication) and some common solutions (deduplication via crate functions)

**Comment by dtolnay** [comment]
I no longer believe this guideline would be worthwhile. Macros 1.0 macro_rules are too much of a mess to push for this now. Let's just wait for macros 2.0 to fix this correctly.
