### ISSUE TITLE
Take R: Read and W: Write by value

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#7]
The standard library contains these two impls:

```rust
impl<'a, R: Read + ?Sized> Read for &'a mut R
impl<'a, W: Write + ?Sized> Write for &'a mut W
```

That means any function that accepts `R: Read` or `W: Write` by value can be called with a mut reference if necessary.

Real examples:

```rust
// from flate2
impl<R: Read> DecoderReader<R> {
    pub fn new(r: R) -> Self
}

// from serde_json
pub fn from_reader<R, T>(rdr: R) -> Result<T> where R: Read, T: Deserialize
```

In the documentation of such functions, briefly remind users that a mut reference can be passed. New Rust users often struggle with this ("I want to deserialize two values from the same fs::File but I passed the file by value so I can't use it anymore").

**Comment by brson** [comment]
"Interop" section.

**Comment by dtolnay** [comment]
Written in eceb521ab9f42493a31eb99e7d42f6f554f3970d.

**Comment by lfairy** [comment]
Can this be a Clippy lint (if it isn't already)?
