### ISSUE TITLE
Steps for checking that your html_root_url is correct

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#77]
Hyper has been using a bad html_root_url since 0.10.7 (https://github.com/hyperium/hyper/issues/1193). Let's explain or link to an explanation of how to pick the right html_root_url so users are not forced to guess.

**Comment by seanmonstar** [comment]
I would much rather this somehow be automated in Cargo or something, maybe via `env!("CARGO_PKG_VERSION")` or something.

**Comment by dtolnay** [comment]
Yes keeping the version updated automatically would be great! That would solve the problem of an outdated version in html_root_url like https://github.com/carllerche/mio/issues/613.

I don't think it would solve https://github.com/hyperium/hyper/commit/aee7c991e6af3e6a4baf528e7ff107f412c7bebf and similar. Rustdoc urls have a tendency to be confusing. Which of these is the right html_root_url?

- `https://hyperium.github.io/hyper/hyper/index.html`
- `https://hyperium.github.io/hyper/hyper/`
- `https://hyperium.github.io/hyper/hyper`
- `https://hyperium.github.io/hyper/`
- `https://hyperium.github.io/hyper`
- `https://hyperium.github.io/`
- `https://hyperium.github.io`

Let's check the book.

> You can control a few aspects of the HTML that `rustdoc` generates through the `#![doc]` version of the attribute:
>
> ```rust
> #![doc(html_logo_url = "https://www.rust-lang.org/logos/rust-logo-128x128-blk-v2.png",
>        html_favicon_url = "https://www.rust-lang.org/favicon.ico",
>        html_root_url = "https://doc.rust-lang.org/")]
> ```
>
> This sets a few different options, with a logo, favicon, and a root URL.

:crying_cat_face:

**Comment by dtolnay** [comment]
The html_root_url attribute is not (yet?) mentioned in the second edition of the book so for now we will need to provide more explanation here than we may like. https://github.com/rust-lang/book/issues/725

**Comment by dtolnay** [comment]
We removed the html_root_url recommendation.
