### ISSUE TITLE
Exceptions for setting html_root_url and documentation to docs.rs

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#78]
The main one I know of is docs.rs only supports documenting the default feature set: https://github.com/onur/docs.rs/issues/29.

Dependency on system libraries may also be a problem.

**Comment by dtolnay** [comment]
Some points against docs.rs in https://github.com/onur/docs.rs/issues/125#issuecomment-301208170.

**Comment by onur** [comment]
Since https://github.com/onur/docs.rs/pull/131 docs.rs is automatically setting html_root_url for crates and it's dependencies. I think `C-HTML-ROOT` can be removed from rust-api-guidelines.

**Comment by dtolnay** [comment]
I removed the html_root_url guideline in 5c457dfa5340fd3ba2ede0ca6d5896c48d1e7d49.

**Comment by CAD97** [comment]
Why was C-HTML-ROOT was re-added in b36cc0d2e232a757c2eef8fd752a8a296798f4bd? It seems that it's not needed anymore. Should it just be re-removed now?

**Comment by dtolnay** [comment]
It still makes a difference for `cargo doc --no-deps` local builds. Without it, rustdoc doesn't link to types from your crate.
