### ISSUE TITLE
Capitalization and punctuation of error messages

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#79]
Libraries seem to be all over the place. Can we standardize on lowercase with no period at the end?

**Comment by dtolnay** [comment]
The standard library uses lowercase without trailing punctuation.

> "unexpected end of file"

> "provided string was not \`true\` or \`false\`"

> "invalid IP address syntax"

> "second time provided was later than self"

> "invalid utf-8 sequence of {} bytes from index {}"

> "environment variable was not valid unicode: {:?}"

**Comment by mehcode** [comment]
In line with this, capitalization and punctuation of `expect` should be discussed. I'm in favor of it being treated the same, however, the std library suggests `expect` messages [should be capitalized](https://doc.rust-lang.org/std/result/enum.Result.html#examples-17) while at the same time using lowercase anywhere [that I looked](https://doc.rust-lang.org/src/core/result.rs.html#738).

**Comment by dtolnay** [comment]
Added in 201d9036dbe8640eef6054d2d9632ea0a0532ab6.
