### ISSUE TITLE
Is DangerousOption a reasonable exception to C-DEREF-FAIL?

### ISSUE THREAD

**Issue by Kixunil** [rust-lang-nursery/api-guidelines#88]
My crate [`DangerousOption`](https://crates.io/crates/dangerous_option) intentionally breaks this rule. Would this be considered a reasonable exception?

**Comment by dtolnay** [comment]
I have come to believe that there are reasonable exceptions to this guideline, and DangerousOption is one of them. I don't think we need to discourage panic in Deref any more than we discourage panic anywhere else, so I removed this guideline in de418dcbf5898490ce0b1cc250fdeca369577d0b. Thanks for reporting this!
