### ISSUE TITLE
Convention for Naming Getters

### ISSUE THREAD

**Issue by theduke** [rust-lang-nursery/api-guidelines#89]
I noticed that the guidelines don't recommend a way to name getters.

```rust
fn get_member(&self) -> &Member
```

vs

```rust
fn member(&self) -> &Member
```

Might be nice to recommend something here.

I'd be strongly in favor of the second option without `get_`.

**Comment by sfackler** [comment]
With very few exceptions (e.g. `get_ref` and `get_mut`), the `get_` prefix is not used in Rust code.

**Comment by alteous** [comment]
```rust
fn member(&self) -> &Member
```
Should be the preferred option.

**Comment by dtolnay** [comment]
Ideally the current "Single-element containers implement appropriate getters" guideline should be expanded to cover getters more generally.

**Comment by dtolnay** [comment]
Let's be sure to touch on the difference between conversions and accessors. As an example, [`TempDir::path`](https://docs.rs/tempdir/0.3.5/tempdir/struct.TempDir.html#method.path) is an accessor so it would not be correct to call it TempDir::as_path.

**Comment by dtolnay** [comment]
I generalized the explanation of getter naming in a80355d86c2102967f7576f2599618f5fc1c6d8a and added a note about getter vs conversion in 5ac0bd004341f6d90f43cd7c325fe845e904c477.
