### ISSUE TITLE
Conventions around into_inner()

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#9]
Real-world example: [`flate2::read::GzEncoder::into_inner`](https://docs.rs/flate2/0.2.17/flate2/read/struct.GzEncoder.html#method.into_inner).

**Comment by dtolnay** [comment]
The failure crate uses inner() instead of into_inner() in https://github.com/withoutboats/failure/commit/9ec4e6ee4cdf9b8be0a8609d876a5654b31b4a70. @withoutboats do you think this is a better convention everywhere that currently uses into_inner(), or is there something unique to failure that made inner() better?

**Comment by withoutboats** [comment]
Nope, if the convention is `into_inner` that would be a better name there!

**Comment by dtolnay** [comment]
I documented this convention in 1bd903f893e29a1470747ced6175f127ea29ba4d.
