### ISSUE TITLE
Recommend that git commit corresponding to each release is tagged

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#91]
This is worth mentioning in the C-RELNOTES guideline.

**Comment by dtolnay** [comment]
Added in b5be84180399cd84d9048eceafd824021b9e3b96.

**Comment by mathstuf** [comment]
It is probably best to also recommend using annotated tags for official releases (the `-a` flag). It should also mention that similar processes should be followed for non-git VCS tools as well.

**Comment by dtolnay** [comment]
Thanks for the ideas! I agree. I added `-a` in ac585b708c07236142d420fc680a21e08367a271 and added a  note about non-git in df9c5e2ed3cc6ad95d624ee46b7162248d4175fd. The wording in this guideline isn't great so please send a PR if you can write it more clearly.

**Comment by mathstuf** [comment]
Annotated tags are used not just for name and email; PR incoming :) .
